/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;


import javax.swing.JOptionPane;


/**
 *
 * @author mzenm
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
  
        initComponents();
        updateStatusLogin();
        
        setLocationRelativeTo(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnListBuku = new javax.swing.JButton();
        menuUtama = new javax.swing.JMenuBar();
        mMasterData = new javax.swing.JMenu();
        miBuku = new javax.swing.JMenuItem();
        miPembeli = new javax.swing.JMenuItem();
        miPemasok = new javax.swing.JMenuItem();
        miPenjualan = new javax.swing.JMenu();
        mLaporan = new javax.swing.JMenu();
        miLaporanBuku = new javax.swing.JMenuItem();
        miLaporanTransaksi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi Penjualan Buku");

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));

        jLabel1.setFont(new java.awt.Font("Calisto MT", 1, 24)); // NOI18N
        jLabel1.setText("APLIKASI PENJUALAN BUKU");

        lblLogin.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login.png"))); // NOI18N
        lblLogin.setText("Login admin");
        lblLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLoginMouseClicked(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Beranda.png"))); // NOI18N

        btnListBuku.setBackground(new java.awt.Color(0, 102, 255));
        btnListBuku.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnListBuku.setText("LIST BUKU");
        btnListBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListBukuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel1)
                .addContainerGap(188, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblLogin)
                        .addGap(21, 21, 21))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnListBuku)
                        .addGap(304, 304, 304))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(btnListBuku)
                .addGap(56, 56, 56)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        mMasterData.setText("Master Data");
        mMasterData.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mMasterData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mMasterDataMouseClicked(evt);
            }
        });
        mMasterData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mMasterDataActionPerformed(evt);
            }
        });

        miBuku.setText("Buku");
        miBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBukuActionPerformed(evt);
            }
        });
        mMasterData.add(miBuku);

        miPembeli.setText("Pembeli");
        miPembeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPembeliActionPerformed(evt);
            }
        });
        mMasterData.add(miPembeli);

        miPemasok.setText("Pemasok");
        miPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPemasokActionPerformed(evt);
            }
        });
        mMasterData.add(miPemasok);

        menuUtama.add(mMasterData);

        miPenjualan.setText("Transaksi");
        miPenjualan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        miPenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                miPenjualanMouseClicked(evt);
            }
        });
        menuUtama.add(miPenjualan);

        mLaporan.setText("Laporan");
        mLaporan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mLaporanMouseClicked(evt);
            }
        });

        miLaporanBuku.setText("Laporan Buku");
        miLaporanBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLaporanBukuActionPerformed(evt);
            }
        });
        mLaporan.add(miLaporanBuku);

        miLaporanTransaksi.setText("Laporan Transaksi");
        miLaporanTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLaporanTransaksiActionPerformed(evt);
            }
        });
        mLaporan.add(miLaporanTransaksi);

        menuUtama.add(mLaporan);

        setJMenuBar(menuUtama);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBukuActionPerformed
        dispose();
        new Buku().setVisible(true);
    }//GEN-LAST:event_miBukuActionPerformed

    private void miPembeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPembeliActionPerformed
        new Pembeli().setVisible(true);
        dispose();
    }//GEN-LAST:event_miPembeliActionPerformed

    private void miPenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_miPenjualanMouseClicked
            if (LoginAdmin.statusLogin) {
            // Jika status login adalah admin, buka jframe TambahKota
        new Penjualan().setVisible(true);
        dispose();
        } else {
            // Jika bukan admin, tampilkan pesan bahwa harus login sebagai admin
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Maaf... Hanya admin yang dapat menggunakan fitur ini...!!!", "Akses Ditolak", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_miPenjualanMouseClicked

    private void miPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPemasokActionPerformed
        new Pemasok().setVisible(true);
        dispose();        
    }//GEN-LAST:event_miPemasokActionPerformed

    private void miLaporanBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLaporanBukuActionPerformed
        new LaporanBuku().setVisible(true);
        dispose();
    }//GEN-LAST:event_miLaporanBukuActionPerformed

    private void miLaporanTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLaporanTransaksiActionPerformed
        new LaporanTransaksi().setVisible(true);
        dispose();
    }//GEN-LAST:event_miLaporanTransaksiActionPerformed

    private void lblLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoginMouseClicked
        if (lblLogin.getText().equals("Login admin")) {
            // Jika label adalah "Login Admin", buka jframe LoginAdmin
            LoginAdmin loginAdmin = new LoginAdmin();
            loginAdmin.setVisible(true);
            this.dispose();
        } else if (lblLogin.getText().equals("Admin")) {
            // Jika label adalah "Admin", tampilkan konfirmasi logout
            int confirm = JOptionPane.showConfirmDialog(this, "Anda yakin ingin keluar sebagai admin?", "Konfirmasi Logout", JOptionPane.YES_NO_OPTION);
            if (confirm == JOptionPane.YES_OPTION) {
                // Jika dikonfirmasi, set status login menjadi false
                LoginAdmin.statusLogin = false;
                JOptionPane.showMessageDialog(null, "Anda Telah keluar sebagai admin");
                // Perbarui teks label menjadi "Masuk Sebagai Admin"
                updateStatusLogin();
            }
        }
    }//GEN-LAST:event_lblLoginMouseClicked

    private void mMasterDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mMasterDataActionPerformed

    }//GEN-LAST:event_mMasterDataActionPerformed

    private void mMasterDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mMasterDataMouseClicked
            if (LoginAdmin.statusLogin) {

        } else {
            // Jika bukan admin, tampilkan pesan bahwa harus login sebagai admin
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Maaf... Hanya admin yang dapat menggunakan fitur ini...!!!", "Akses Ditolak", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_mMasterDataMouseClicked

    private void mLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mLaporanMouseClicked
            if (LoginAdmin.statusLogin) {

        } else {
            // Jika bukan admin, tampilkan pesan bahwa harus login sebagai admin
            getToolkit().beep();
            JOptionPane.showMessageDialog(this, "Maaf... Hanya admin yang dapat menggunakan fitur ini...!!!", "Akses Ditolak", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_mLaporanMouseClicked

    private void btnListBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListBukuActionPerformed
        new ListBuku().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnListBukuActionPerformed

        private void updateStatusLogin() {
   if (LoginAdmin.statusLogin) {
        // Jika sudah login, ganti teks label menjadi "Admin"
        lblLogin.setText("Admin");
    } else {
        // Jika belum login, biarkan teks label menjadi "Login Admin"
        lblLogin.setText("Login admin");
    }
}
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListBuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JMenu mLaporan;
    private javax.swing.JMenu mMasterData;
    private javax.swing.JMenuBar menuUtama;
    private javax.swing.JMenuItem miBuku;
    private javax.swing.JMenuItem miLaporanBuku;
    private javax.swing.JMenuItem miLaporanTransaksi;
    private javax.swing.JMenuItem miPemasok;
    private javax.swing.JMenuItem miPembeli;
    private javax.swing.JMenu miPenjualan;
    // End of variables declaration//GEN-END:variables
}
