/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

//Import library database
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

//Import library GUI
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.HashMap;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import java.awt.event.KeyEvent;
import net.sf.jasperreports.engine.DefaultJasperReportsContext;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperReportsContext;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author mzenm
 */
public class Pemasok extends javax.swing.JFrame {
    
    Connection con; //koneksi
    ResultSet rs;   //query
    PreparedStatement pst; //manipulasi database

    /**
     * Creates new form Pemasok
     */
    public Pemasok() {
        initComponents();
        
        setLocationRelativeTo(null);
                
            try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/penjualan_buku", "root", "");
        
        String sql = "SELECT * FROM pemasok";
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        
        while (rs.next()){
         // menampilkan data buku ke table
         String id = String.valueOf(rs.getString("id"));
         String nama = String.valueOf(rs.getString("nama"));
         String no_telepon = String.valueOf(rs.getString("no_telepon"));
         String alamat = String.valueOf(rs.getString("alamat"));
         
         String tbData[] = {id, nama, no_telepon, alamat};
         DefaultTableModel tampilModel = (DefaultTableModel) tblPemasok.getModel();

         tampilModel.addRow(tbData);
         }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, "MySQL JDBC Driver not found", ex);
        } catch (SQLException ex) {
            Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, null, ex);
        }
            
           // Menghitung jumlah pemasok
            try{
                pst = con.prepareStatement("SELECT COUNT(*) AS jumlahPemasok FROM pemasok");
                ResultSet rs = pst.executeQuery();
                while(rs.next())
                {
                    int count = rs.getInt("jumlahPemasok");

                    lblJumlah.setText(String.valueOf(count));
                }
            } catch (SQLException ex) {
                Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, null, ex);
            }            
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        utamaPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        lblForm = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        inputanPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPemasok = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfNoTelpon = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAlamat = new javax.swing.JTextArea();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        navigasiPanel = new javax.swing.JPanel();
        tfCari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCetak = new javax.swing.JButton();
        outputPanel = new javax.swing.JPanel();
        jumlahPemasokPanel = new javax.swing.JPanel();
        lblJumlah = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        utamaPanel.setBackground(new java.awt.Color(0, 204, 204));

        headerPanel.setBackground(new java.awt.Color(204, 255, 255));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblForm.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        lblForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Pemasok.png"))); // NOI18N
        lblForm.setText("FORM PEMASOK");
        headerPanel.add(lblForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 190, 59));

        btnKembali.setBackground(new java.awt.Color(0, 204, 204));
        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Kembali.png"))); // NOI18N
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        headerPanel.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 40, 40));

        inputanPanel.setBackground(new java.awt.Color(204, 255, 255));

        tblPemasok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Pemasok", "Nomor Telpon", "Alamat"
            }
        ));
        tblPemasok.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblPemasok.setGridColor(new java.awt.Color(153, 153, 153));
        tblPemasok.setSelectionBackground(new java.awt.Color(153, 204, 255));
        tblPemasok.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblPemasok.setShowHorizontalLines(true);
        tblPemasok.setShowVerticalLines(true);
        tblPemasok.getTableHeader().setReorderingAllowed(false);
        tblPemasok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPemasokMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPemasok);
        if (tblPemasok.getColumnModel().getColumnCount() > 0) {
            tblPemasok.getColumnModel().getColumn(0).setMinWidth(40);
            tblPemasok.getColumnModel().getColumn(0).setMaxWidth(40);
            tblPemasok.getColumnModel().getColumn(1).setMinWidth(180);
            tblPemasok.getColumnModel().getColumn(1).setMaxWidth(180);
            tblPemasok.getColumnModel().getColumn(2).setMinWidth(145);
            tblPemasok.getColumnModel().getColumn(2).setMaxWidth(145);
            tblPemasok.getColumnModel().getColumn(3).setMinWidth(206);
            tblPemasok.getColumnModel().getColumn(3).setMaxWidth(206);
        }

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Pemasok", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1.setText("ID");

        jLabel2.setText("Nama");

        jLabel4.setText("Alamat");

        jLabel6.setText(":");

        jLabel9.setText(":");

        jLabel11.setText(":");

        jLabel15.setText("No Telepon");

        tfNoTelpon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNoTelponKeyTyped(evt);
            }
        });

        jLabel16.setText(":");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        taAlamat.setColumns(20);
        taAlamat.setRows(5);
        jScrollPane2.setViewportView(taAlamat);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfNoTelpon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addComponent(tfId, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNama, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNoTelpon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel11))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        btnTambah.setBackground(new java.awt.Color(102, 153, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Tambah.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(255, 153, 102));
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Ubah.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 51, 51));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Hapus.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(163, 133, 104));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputanPanelLayout = new javax.swing.GroupLayout(inputanPanel);
        inputanPanel.setLayout(inputanPanelLayout);
        inputanPanelLayout.setHorizontalGroup(
            inputanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputanPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(inputanPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        inputanPanelLayout.setVerticalGroup(
            inputanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputanPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(inputanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(inputanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnClear))
                .addGap(19, 19, 19))
        );

        navigasiPanel.setBackground(new java.awt.Color(204, 255, 255));

        tfCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCariKeyReleased(evt);
            }
        });

        jLabel3.setText("Cari :");

        btnCetak.setBackground(new java.awt.Color(0, 153, 102));
        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cetak.png"))); // NOI18N
        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigasiPanelLayout = new javax.swing.GroupLayout(navigasiPanel);
        navigasiPanel.setLayout(navigasiPanelLayout);
        navigasiPanelLayout.setHorizontalGroup(
            navigasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigasiPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(288, 288, 288)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        navigasiPanelLayout.setVerticalGroup(
            navigasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigasiPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(navigasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCetak))
                .addGap(13, 13, 13))
        );

        outputPanel.setBackground(new java.awt.Color(204, 255, 255));
        outputPanel.setPreferredSize(new java.awt.Dimension(250, 126));

        jumlahPemasokPanel.setBackground(new java.awt.Color(0, 204, 204));
        jumlahPemasokPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jumlah Pemasok", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jumlahPemasokPanel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblJumlah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jumlahPemasokPanelLayout = new javax.swing.GroupLayout(jumlahPemasokPanel);
        jumlahPemasokPanel.setLayout(jumlahPemasokPanelLayout);
        jumlahPemasokPanelLayout.setHorizontalGroup(
            jumlahPemasokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jumlahPemasokPanelLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(lblJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jumlahPemasokPanelLayout.setVerticalGroup(
            jumlahPemasokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jumlahPemasokPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout outputPanelLayout = new javax.swing.GroupLayout(outputPanel);
        outputPanel.setLayout(outputPanelLayout);
        outputPanelLayout.setHorizontalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jumlahPemasokPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        outputPanelLayout.setVerticalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jumlahPemasokPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout utamaPanelLayout = new javax.swing.GroupLayout(utamaPanel);
        utamaPanel.setLayout(utamaPanelLayout);
        utamaPanelLayout.setHorizontalGroup(
            utamaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, utamaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(utamaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(navigasiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outputPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                    .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(inputanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        utamaPanelLayout.setVerticalGroup(
            utamaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utamaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navigasiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(utamaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(utamaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void tblPemasokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPemasokMouseClicked
        //Menampilkan Data dari Jtable ke TextFiled
        int selectedRow = tblPemasok.getSelectedRow();

        DefaultTableModel model = (DefaultTableModel) tblPemasok.getModel();
        tfId.setText(model.getValueAt(selectedRow, 0).toString());
        tfNama.setText(model.getValueAt(selectedRow, 1).toString());
        tfNoTelpon.setText(model.getValueAt(selectedRow, 2).toString());
        taAlamat.setText(model.getValueAt(selectedRow, 3).toString());

    }//GEN-LAST:event_tblPemasokMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
       //Mengecek nilai yang di input
        if (tfId.getText().equals("") || tfNama.getText().equals("") || 
        tfNoTelpon.getText().equals("") || taAlamat.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Lengkapi Data Yang Kosong..!",
                "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            // Pemeriksaan ID tidak boleh sama
            boolean IdSudahAda = false;
            DefaultTableModel model = (DefaultTableModel) tblPemasok.getModel();

            for (int i = 0; i < model.getRowCount(); i++) {
                if (tfId.getText().equals(model.getValueAt(i, 0))) {
                    IdSudahAda = true;
                    break;
                }
            }

            if (IdSudahAda) {
                JOptionPane.showMessageDialog(null, "ID sudah terdaftar, masukkan ID yang berbeda",
                    "Error", JOptionPane.WARNING_MESSAGE);
                tfId.requestFocus();
            } else {
                
        //Membuat koneksi agar dapat menipulasi data Pemasok pada Database
        try {
            pst = con.prepareStatement("INSERT into pemasok(id,nama,no_telepon,alamat)values(?,?,?,?)");
            int id   = Integer.parseInt(tfId.getText());
            pst.setString(1, tfId.getText());
            pst.setString(2, tfNama.getText());
            pst.setString(3, tfNoTelpon.getText());
            pst.setString(4, taAlamat.getText());

            pst.executeUpdate();

        } catch (SQLException ex) {
            Logger.getLogger(Pemasok.class.getName()).log(Level.SEVERE, null, ex);
        }

 
       // Menambahkan data ke dalam row
       int id   = Integer.parseInt(tfId.getText());
       model.addRow(new Object[]{ tfId.getText(), tfNama.getText(),
            tfNoTelpon.getText(), taAlamat.getText()});
       JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
       // Menghitung jumlah pemasok
            try{
                pst = con.prepareStatement("SELECT COUNT(*) AS jumlahPemasok FROM pemasok");
                ResultSet rs = pst.executeQuery();
                while(rs.next())
                {
                    int count = rs.getInt("jumlahPemasok");

                    lblJumlah.setText(String.valueOf(count));
                }
            } catch (SQLException ex) {
                Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        //Membersihkan field setelah data berhasil terinput
        tfId.setText("");
        tfNama.setText("");
        tfNoTelpon.setText("");
        taAlamat.setText("");
        tfId.requestFocus();
            }
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        //Mengecek pemilihan data
        if (tfId.getText().equals("") || tfNama.getText().equals("") ||
                tfNoTelpon.getText().equals("") || taAlamat.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pilih Data Terlebih Dahulu..!",
                "Error", JOptionPane.WARNING_MESSAGE);
        }else{

            //Konfirmasi ubah data
            int hapus = JOptionPane.showConfirmDialog(null, "Anda yakin mengubah data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (hapus == JOptionPane.YES_OPTION) {

                try {
                    // Mengubah data dalam database
                    pst = con.prepareStatement("UPDATE pemasok SET id=?, nama=?, no_telepon=?, alamat=? WHERE id=?");
                    int id   = Integer.parseInt(tfId.getText());
                    pst.setString(1, tfId.getText());
                    pst.setString(2, tfNama.getText());
                    pst.setString(3, tfNoTelpon.getText());
                    pst.setString(4, taAlamat.getText());
                    pst.setString(5, tfId.getText());

                    pst.executeUpdate();
                    pst.close();

                    JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");


            // Mengubah data dalam row di tabel
            int selectedRow = tblPemasok.getSelectedRow();
            if (selectedRow >= 0) {
                DefaultTableModel model = (DefaultTableModel) tblPemasok.getModel();
                model.setValueAt(tfId.getText(), selectedRow, 0);
                model.setValueAt(tfNama.getText(), selectedRow, 1);
                model.setValueAt(tfNoTelpon.getText(), selectedRow, 2);
                model.setValueAt(taAlamat.getText(), selectedRow, 3); 
                    }
                    //Membersihkan field setelah data berhasil diubah
                    tfId.setText("");
                    tfNama.setText("");
                    tfNoTelpon.setText("");
                    taAlamat.setText("");
                    tfId.requestFocus();

                } catch (SQLException ex) {
                    Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        //Mengecek pemilihan data
        if (tfId.getText().equals("") || tfNama.getText().equals("") ||
                tfNoTelpon.getText().equals("") || taAlamat.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Pilih Data Terlebih Dahulu..!",
                "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            //Konfirmasi hapus data
            int ubah = JOptionPane.showConfirmDialog(null, "Anda yakin menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
            if (ubah == JOptionPane.YES_OPTION) {

                // Menghapus data dalam database
                try {
                    pst = con.prepareStatement("DELETE FROM pemasok WHERE id=?");
                    pst.setString(1, tfId.getText());
                    pst.executeUpdate();
                    pst.close(); // Menutup PreparedStatement setelah digunakan
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");

                } catch (SQLException ex) {
                    Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, null, ex);
                }

                           // Menghitung jumlah pemasok
            try{
                pst = con.prepareStatement("SELECT COUNT(*) AS jumlahPemasok FROM pemasok");
                ResultSet rs = pst.executeQuery();
                while(rs.next())
                {
                    int count = rs.getInt("jumlahPemasok");

                    lblJumlah.setText(String.valueOf(count));
                }
            } catch (SQLException ex) {
                Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, null, ex);
            }
            
                //Membersihkan inputan
                tfId.setText("");
                tfNama.setText("");
                tfNoTelpon.setText("");
                taAlamat.setText("");
                tfId.requestFocus();
                //Menghapus data dalam row
                int getSelectedRowForDeletion = tblPemasok.getSelectedRow();
                if (getSelectedRowForDeletion >= 0) {
                    DefaultTableModel model = (DefaultTableModel) tblPemasok.getModel();
                    model.removeRow(getSelectedRowForDeletion);
                    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                }
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        tfId.setText("");
        tfNama.setText("");
        tfNoTelpon.setText("");
        taAlamat.setText("");
        tfId.requestFocus();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/penjualan_buku", "root", "");

        HashMap<String, Object> parameters = new HashMap<>();
        String reportpath = "src/report/ReportPemasok.jrxml";
        JasperReport jr = JasperCompileManager.compileReport(reportpath);
        
        // Add the following line to resolve the namespace warning
        JasperReportsContext jasperReportsContext = DefaultJasperReportsContext.getInstance();
        jasperReportsContext.setProperty("net.sf.jasperreports.components.html.factory", "net.sf.jasperreports.components.html.HtmlComponentFactory");

        JasperPrint jp = JasperFillManager.fillReport(jr, parameters, conn);
        JasperViewer viewer = new JasperViewer(jp, false);
        viewer.setVisible(true);
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void tfCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCariKeyReleased
        DefaultTableModel model=(DefaultTableModel) tblPemasok.getModel();
        TableRowSorter<DefaultTableModel> model1= new TableRowSorter<>(model);
        tblPemasok.setRowSorter(model1);
        model1.setRowFilter(RowFilter.regexFilter(tfCari.getText()));
    }//GEN-LAST:event_tfCariKeyReleased

    private void tfNoTelponKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNoTelponKeyTyped
        //memanggil method KeyTyped
        filterKeyTyped(evt);
        tfNoTelpon.requestFocus();
    }//GEN-LAST:event_tfNoTelponKeyTyped

   //Membuat method filter Nilai harus berupa angka
    private void filterKeyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
        if (!((Character.isDigit(c)
                || (c == KeyEvent.VK_BACK_SPACE)
                || (c == KeyEvent.VK_DELETE)))) {
            getToolkit().beep();
            JOptionPane.showMessageDialog(null, "Error..!!!Masukan Hanya Angka ");
            evt.consume();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pemasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pemasok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel inputanPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jumlahPemasokPanel;
    private javax.swing.JLabel lblForm;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JPanel navigasiPanel;
    private javax.swing.JPanel outputPanel;
    private javax.swing.JTextArea taAlamat;
    private javax.swing.JTable tblPemasok;
    private javax.swing.JTextField tfCari;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNoTelpon;
    private javax.swing.JPanel utamaPanel;
    // End of variables declaration//GEN-END:variables
}
