/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

//Import library database
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;

//Import library GUI
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.HashMap;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.DefaultJasperReportsContext;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.JasperReportsContext;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author mzenm
 */
public class Pembeli extends javax.swing.JFrame {
    
    Connection con; //koneksi
    ResultSet rs;   //query
    PreparedStatement pst; //manipulasi database

    /**
     * Creates new form Pembeli
     */
    public Pembeli() {
        initComponents();
        
        setLocationRelativeTo(null);
                
        
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/penjualan_buku", "root", "");
        
        String sql = "SELECT * FROM pembeli";
        pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        
        while (rs.next()){
         // menampilkan data buku ke table
         String id = String.valueOf(rs.getString("id"));
         String nama = String.valueOf(rs.getString("nama"));
         String jenis_kelamin = String.valueOf(rs.getString("jenis_kelamin"));
         String no_telepon = String.valueOf(rs.getString("no_telepon"));
         String alamat = String.valueOf(rs.getString("alamat"));
         
         String tbData[] = {id, nama, jenis_kelamin, no_telepon, alamat};
         DefaultTableModel tampilModel = (DefaultTableModel) tblPembeli.getModel();

         tampilModel.addRow(tbData);
         }
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, "MySQL JDBC Driver not found", ex);
        } catch (SQLException ex) {
            Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, null, ex);
        }
   
    try{
        pst = con.prepareStatement("SELECT COUNT(*) AS jumlahPembeli FROM pembeli");
        ResultSet rs = pst.executeQuery();
        while(rs.next())
        {
            int count = rs.getInt("jumlahPembeli");
            
            lblJumlah.setText(String.valueOf(count));
        }
    } catch (SQLException ex) {
        Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    //Membuat grup agar radio buton hanya dapat dipilih maksimal satu  
    ButtonGroup buttonGroup = new ButtonGroup();
    buttonGroup.add(rbLaki);
    buttonGroup.add(rbPerempuan);
    rbLaki.setSelected(true);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        utamaPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        lblForm = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        inputanPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPembeli = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        tfNama = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfNoTelpon = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taAlamat = new javax.swing.JTextArea();
        rbLaki = new javax.swing.JRadioButton();
        rbPerempuan = new javax.swing.JRadioButton();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        navigasiPanel = new javax.swing.JPanel();
        tfCari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnCetak = new javax.swing.JButton();
        outputPanel = new javax.swing.JPanel();
        jumlahPembeliPanel = new javax.swing.JPanel();
        lblJumlah = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Pembeli");

        utamaPanel.setBackground(new java.awt.Color(0, 153, 102));

        headerPanel.setBackground(new java.awt.Color(204, 255, 204));
        headerPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblForm.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        lblForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Pembeli.png"))); // NOI18N
        lblForm.setText("FORM PEMBELI");
        headerPanel.add(lblForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 59));

        btnKembali.setBackground(new java.awt.Color(0, 204, 153));
        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Kembali.png"))); // NOI18N
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        headerPanel.add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 10, 40, 40));

        inputanPanel.setBackground(new java.awt.Color(204, 255, 204));

        tblPembeli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nama Pembeli", "Jenis Kelamin", "Nomor Telpon", "Alamat"
            }
        ));
        tblPembeli.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tblPembeli.setGridColor(new java.awt.Color(153, 153, 153));
        tblPembeli.setSelectionBackground(new java.awt.Color(153, 204, 255));
        tblPembeli.setSelectionForeground(new java.awt.Color(255, 255, 255));
        tblPembeli.setShowHorizontalLines(true);
        tblPembeli.setShowVerticalLines(true);
        tblPembeli.getTableHeader().setReorderingAllowed(false);
        tblPembeli.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPembeliMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPembeli);
        if (tblPembeli.getColumnModel().getColumnCount() > 0) {
            tblPembeli.getColumnModel().getColumn(0).setMinWidth(35);
            tblPembeli.getColumnModel().getColumn(0).setMaxWidth(35);
            tblPembeli.getColumnModel().getColumn(1).setMinWidth(150);
            tblPembeli.getColumnModel().getColumn(1).setMaxWidth(150);
            tblPembeli.getColumnModel().getColumn(2).setMinWidth(100);
            tblPembeli.getColumnModel().getColumn(2).setMaxWidth(100);
            tblPembeli.getColumnModel().getColumn(3).setMinWidth(100);
            tblPembeli.getColumnModel().getColumn(3).setMaxWidth(100);
            tblPembeli.getColumnModel().getColumn(4).setMinWidth(172);
            tblPembeli.getColumnModel().getColumn(4).setMaxWidth(172);
        }

        jPanel2.setBackground(new java.awt.Color(0, 204, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Input Pembeli", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jLabel1.setText("ID");

        jLabel2.setText("Nama");

        jLabel4.setText("Alamat");

        jLabel6.setText(":");

        jLabel9.setText(":");

        jLabel11.setText(":");

        jLabel13.setText("Jenis Kelamin");

        jLabel14.setText(":");

        jLabel15.setText("No Telepon");

        jLabel16.setText(":");

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        taAlamat.setColumns(20);
        taAlamat.setRows(5);
        jScrollPane2.setViewportView(taAlamat);

        rbLaki.setText("Laki-laki");

        rbPerempuan.setText("Perempuan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(rbLaki)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbPerempuan)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfNoTelpon, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfId, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfNama, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(19, 19, 19))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel9)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(rbLaki)
                    .addComponent(rbPerempuan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNoTelpon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel4))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        btnTambah.setBackground(new java.awt.Color(102, 153, 255));
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Tambah.png"))); // NOI18N
        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setBackground(new java.awt.Color(255, 153, 102));
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Ubah.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 51, 51));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Hapus.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(153, 153, 0));
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Clear.png"))); // NOI18N
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputanPanelLayout = new javax.swing.GroupLayout(inputanPanel);
        inputanPanel.setLayout(inputanPanelLayout);
        inputanPanelLayout.setHorizontalGroup(
            inputanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputanPanelLayout.createSequentialGroup()
                .addGroup(inputanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inputanPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(inputanPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71)
                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        inputanPanelLayout.setVerticalGroup(
            inputanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputanPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(inputanPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnClear))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        navigasiPanel.setBackground(new java.awt.Color(204, 255, 204));

        tfCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCariKeyReleased(evt);
            }
        });

        jLabel3.setText("Cari :");

        btnCetak.setBackground(new java.awt.Color(0, 153, 102));
        btnCetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Cetak.png"))); // NOI18N
        btnCetak.setText("Cetak");
        btnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navigasiPanelLayout = new javax.swing.GroupLayout(navigasiPanel);
        navigasiPanel.setLayout(navigasiPanelLayout);
        navigasiPanelLayout.setHorizontalGroup(
            navigasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigasiPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCetak, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(274, 274, 274)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        navigasiPanelLayout.setVerticalGroup(
            navigasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navigasiPanelLayout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(navigasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(navigasiPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(btnCetak))
                .addGap(14, 14, 14))
        );

        outputPanel.setBackground(new java.awt.Color(204, 255, 204));

        jumlahPembeliPanel.setBackground(new java.awt.Color(0, 204, 153));
        jumlahPembeliPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jumlah Pembeli", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        jumlahPembeliPanel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblJumlah.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jumlahPembeliPanelLayout = new javax.swing.GroupLayout(jumlahPembeliPanel);
        jumlahPembeliPanel.setLayout(jumlahPembeliPanelLayout);
        jumlahPembeliPanelLayout.setHorizontalGroup(
            jumlahPembeliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jumlahPembeliPanelLayout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(lblJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jumlahPembeliPanelLayout.setVerticalGroup(
            jumlahPembeliPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jumlahPembeliPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout outputPanelLayout = new javax.swing.GroupLayout(outputPanel);
        outputPanel.setLayout(outputPanelLayout);
        outputPanelLayout.setHorizontalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(jumlahPembeliPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(670, Short.MAX_VALUE))
        );
        outputPanelLayout.setVerticalGroup(
            outputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputPanelLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jumlahPembeliPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout utamaPanelLayout = new javax.swing.GroupLayout(utamaPanel);
        utamaPanel.setLayout(utamaPanelLayout);
        utamaPanelLayout.setHorizontalGroup(
            utamaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, utamaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(utamaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(navigasiPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(outputPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(headerPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 889, Short.MAX_VALUE)
                    .addComponent(inputanPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        utamaPanelLayout.setVerticalGroup(
            utamaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(utamaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(navigasiPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputanPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(outputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(utamaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(utamaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblPembeliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPembeliMouseClicked
        //Menampilkan Data dari Jtable ke TextFiled
        int selectedRow = tblPembeli.getSelectedRow();
        
        DefaultTableModel model = (DefaultTableModel) tblPembeli.getModel();
        tfId.setText(model.getValueAt(selectedRow, 0).toString());
        tfNama.setText(model.getValueAt(selectedRow, 1).toString());
        
        String jenisKelamin = model.getValueAt(selectedRow, 2).toString();
        if ("Laki-Laki".equals(jenisKelamin)) {
            rbLaki.setSelected(true);
            rbPerempuan.setSelected(false);
        } else if ("Perempuan".equals(jenisKelamin)) {
            rbLaki.setSelected(false);
            rbPerempuan.setSelected(true);
        }
        tfNoTelpon.setText(model.getValueAt(selectedRow, 3).toString());
        taAlamat.setText(model.getValueAt(selectedRow, 4).toString());
        
    }//GEN-LAST:event_tblPembeliMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
     //Mengecek nilai yang di input
     if (tfId.getText().equals("") || tfNama.getText().equals("") || (!rbLaki.isSelected() && !rbPerempuan.isSelected()) ||
        tfNoTelpon.getText().equals("") || taAlamat.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Lengkapi Data Yang Kosong..!",
            "Error", JOptionPane.WARNING_MESSAGE);
    } else {
     // Pemeriksaan ID tidak boleh sama
    boolean IdSudahAda = false;
    DefaultTableModel model = (DefaultTableModel) tblPembeli.getModel();

    for (int i = 0; i < model.getRowCount(); i++) {
        if (tfId.getText().equals(model.getValueAt(i, 0))) {
            IdSudahAda = true;
            break;
        }
    }

    if (IdSudahAda) {
        JOptionPane.showMessageDialog(null, "ID sudah terdaftar, masukkan ID yang berbeda",
                "Error", JOptionPane.WARNING_MESSAGE);
    } else {
        
    //Membuat koneksi agar dapat menipulasi data Pembeli pada Database  
    try {
        pst = con.prepareStatement("INSERT into pembeli(id,nama,jenis_kelamin,no_telepon,alamat)values(?,?,?,?,?)");
        int id   = Integer.parseInt(tfId.getText());
        pst.setString(1, tfId.getText());
        pst.setString(2, tfNama.getText());
        if (rbLaki.isSelected()) {
        pst.setString(3, "Laki-Laki");
        } else if (rbPerempuan.isSelected()) {
        pst.setString(3, "Perempuan");
        }
        pst.setString(4, tfNoTelpon.getText());
        pst.setString(5, taAlamat.getText());
 
        pst.executeUpdate();
    
    } catch (SQLException ex) {
        Logger.getLogger(Pembeli.class.getName()).log(Level.SEVERE, null, ex);
    }     
        
     // Menambahkan data ke dalam row
    int id   = Integer.parseInt(tfId.getText());
    String jenisKelamin = null;
    if (rbLaki.isSelected()) {
        jenisKelamin = "Laki-Laki";
    } else if (rbPerempuan.isSelected()) {
        jenisKelamin = "Perempuan";
    }
    model.addRow(new Object[]{ tfId.getText(), tfNama.getText(), jenisKelamin,
                              tfNoTelpon.getText(), taAlamat.getText()});
    JOptionPane.showMessageDialog(null, "Data Berhasil Ditambahkan");
    
    try{
        pst = con.prepareStatement("SELECT COUNT(*) AS jumlahPembeli FROM pembeli");
        ResultSet rs = pst.executeQuery();
        while(rs.next())
        {
            int count = rs.getInt("jumlahPembeli");
            
            lblJumlah.setText(String.valueOf(count));
        }
    } catch (SQLException ex) {
        Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, null, ex);
    }
    
        //Membersihkan field setelah data berhasil terinput
        tfId.setText("");
        tfNama.setText("");
        rbLaki.setSelected(false);
        rbPerempuan.setSelected(false);
        tfNoTelpon.setText("");
        taAlamat.setText("");
        tfId.requestFocus();
    }
}
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        //Mengecek pemilihan data
            if (tfId.getText().equals("") || tfNama.getText().equals("") || (!rbLaki.isSelected() && !rbPerempuan.isSelected()) ||
        tfNoTelpon.getText().equals("") || taAlamat.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Pilih Data Terlebih Dahulu..!",
            "Error", JOptionPane.WARNING_MESSAGE);
        }else{
    
        
        //Konfirmasi ubah data  
        int ubah = JOptionPane.showConfirmDialog(null, "Anda yakin mengubah data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
                if (ubah == JOptionPane.YES_OPTION) {
                   
            try {
                // Mengubah data dalam database
            pst = con.prepareStatement("UPDATE pembeli SET id=?, nama=?, jenis_kelamin=?, no_telepon=?, alamat=? WHERE id=?");
            int id   = Integer.parseInt(tfId.getText());
            pst.setString(1, tfId.getText());
            pst.setString(2, tfNama.getText());
            if (rbLaki.isSelected()) {
                pst.setString(3, "Laki-Laki");
            } else if (rbPerempuan.isSelected()) {
                pst.setString(3, "Perempuan");
            }
            pst.setString(4, tfNoTelpon.getText());
            pst.setString(5, taAlamat.getText());
            pst.setString(6, tfId.getText());

            pst.executeUpdate();
            pst.close();

            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");

            // Mengubah data dalam row di tabel
            int selectedRow = tblPembeli.getSelectedRow();
            if (selectedRow >= 0) {
                DefaultTableModel model = (DefaultTableModel) tblPembeli.getModel();
                model.setValueAt(tfId.getText(), selectedRow, 0);
                model.setValueAt(tfNama.getText(), selectedRow, 1);
                if (rbLaki.isSelected()) {
                    model.setValueAt("Laki-Laki", selectedRow, 2);
                } else if (rbPerempuan.isSelected()) {
                    model.setValueAt("Perempuan", selectedRow, 2);
                }
                model.setValueAt(tfNoTelpon.getText(), selectedRow, 3);
                model.setValueAt(taAlamat.getText(), selectedRow, 4);
            }
        //Membersihkan field setelah data berhasil diubah
        tfId.setText("");
        tfNama.setText("");
        rbLaki.setSelected(false);
        rbPerempuan.setSelected(false);
        tfNoTelpon.setText("");
        taAlamat.setText("");
        tfId.requestFocus();
        
        } catch (SQLException ex) {
            Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    //Mengecek pemilihan data
    if (tfId.getText().equals("") || tfNama.getText().equals("") || (!rbLaki.isSelected() && !rbPerempuan.isSelected()) ||
        tfNoTelpon.getText().equals("") || taAlamat.getText().equals("")) {
        JOptionPane.showMessageDialog(null, "Pilih Data Terlebih Dahulu..!",
            "Error", JOptionPane.WARNING_MESSAGE);
     }else{
    //Konfirmasi hapus data
    int ubah = JOptionPane.showConfirmDialog(null, "Anda yakin menghapus data?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
           if (ubah == JOptionPane.YES_OPTION) {
               
    // Menghapus data dalam database
        try {
    pst = con.prepareStatement("DELETE FROM pembeli WHERE id=?");
    pst.setString(1, tfId.getText());
    pst.executeUpdate();
    pst.close(); // Menutup PreparedStatement setelah digunakan
    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
    
} catch (SQLException ex) {
    Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, null, ex);
}
     
    //Membersihkan inputan
    tfId.setText("");
    tfNama.setText("");
    rbLaki.setSelected(false);
    rbPerempuan.setSelected(false);
    tfNoTelpon.setText("");
    taAlamat.setText("");
    tfId.requestFocus();
    
        try{
        pst = con.prepareStatement("SELECT COUNT(*) AS jumlahPembeli FROM pembeli");
        ResultSet rs = pst.executeQuery();
        while(rs.next())
        {
            int count = rs.getInt("jumlahPembeli");
            
            lblJumlah.setText(String.valueOf(count));
        }
    } catch (SQLException ex) {
        Logger.getLogger(Buku.class.getName()).log(Level.SEVERE, null, ex);
    }
        
    //Menghapus data dalam row
    int getSelectedRowForDeletion = tblPembeli.getSelectedRow();
    if (getSelectedRowForDeletion >= 0) {
        DefaultTableModel model = (DefaultTableModel) tblPembeli.getModel();
        model.removeRow(getSelectedRowForDeletion);
        JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus"); 
         }
           }
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        tfId.setText("");
        tfNama.setText("");
        rbLaki.setSelected(false);
        rbPerempuan.setSelected(false);
        tfNoTelpon.setText("");
        taAlamat.setText("");
        tfId.requestFocus();
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakActionPerformed
        // Mengecek data masih kosong dalam row
    try {
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/penjualan_buku", "root", "");

        HashMap<String, Object> parameters = new HashMap<>();
        String reportpath = "src/report/ReportPembeli.jrxml";
        JasperReport jr = JasperCompileManager.compileReport(reportpath);
        
        // Add the following line to resolve the namespace warning
        JasperReportsContext jasperReportsContext = DefaultJasperReportsContext.getInstance();
        jasperReportsContext.setProperty("net.sf.jasperreports.components.html.factory", "net.sf.jasperreports.components.html.HtmlComponentFactory");

        JasperPrint jp = JasperFillManager.fillReport(jr, parameters, conn);
        JasperViewer viewer = new JasperViewer(jp, false);
        viewer.setVisible(true);
        conn.close();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e);
    }
    }//GEN-LAST:event_btnCetakActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        new MenuUtama().setVisible(true);
        dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void tfCariKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCariKeyReleased
        DefaultTableModel model=(DefaultTableModel) tblPembeli.getModel();
        TableRowSorter<DefaultTableModel> model1= new TableRowSorter<>(model);
        tblPembeli.setRowSorter(model1);
        model1.setRowFilter(RowFilter.regexFilter(tfCari.getText()));
    }//GEN-LAST:event_tfCariKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembeli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembeli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCetak;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel inputanPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jumlahPembeliPanel;
    private javax.swing.JLabel lblForm;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JPanel navigasiPanel;
    private javax.swing.JPanel outputPanel;
    private javax.swing.JRadioButton rbLaki;
    private javax.swing.JRadioButton rbPerempuan;
    private javax.swing.JTextArea taAlamat;
    private javax.swing.JTable tblPembeli;
    private javax.swing.JTextField tfCari;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfNoTelpon;
    private javax.swing.JPanel utamaPanel;
    // End of variables declaration//GEN-END:variables
}
